### ISSUE TITLE
ssl错误

### ISSUE THREAD

**Issue by Jacob-Gao** [zhaopeiym/quartzui#83]
报错信息： at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Host.HttpHelper.GetAsync(String url, Dictionary`2 headers) in /src/Host/Common/HttpHelper.cs:line 106
   at Host.HttpJob.NextExecute(IJobExecutionContext context) in /src/Host/IJobs/HttpJob.cs:line 41
   at Host.IJobs.JobBase`1.Execute(IJobExecutionContext context) in /src/Host/IJobs/JobBase.cs:line 55
2022-07-20 17:20:59.030 +08:00 [Error] {"Url":"https://szhaeapp113.apac.bosch.com:447/api/Job/RunEcuFPYData","RequestType":"Get","Parameters":null,"JobName":"default.Test","Result":null,"ErrorMsg":"<span class='error'>The SSL connection could not be established, see inner exception.</span>"}
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

我的URL：https://szhaeapp113.apac.bosch.com:447/api/Job/RunEcuFPYData
证书是自签名的，quartzui是容器跑的。 看日志是quartzui向url发起get,post之类的请求报不信任证书。请问这个如何解决？

**Comment by Jacob-Gao** [comment]
已解决，导入证书在/usr/local/share/ca-certificates   update下即可
